"""SEO page definitions — FR/EN pairs with localized copy (not word-for-word)."""

PAGES = [
    {
        "id": "about",
        "type": "AboutPage",
        "priority": "0.9",
        "fr": {
            "path": "/fr/a-propos/",
            "title": "À propos de Kamaloka AI Technologies — Laboratoire IA & venture studio",
            "description": "Kamaloka AI Technologies LLC : laboratoire technologique et studio de ventures basé à Abidjan. IA, cybersécurité, logiciels et automatisation pour l'Afrique et le monde.",
            "h1": "Kamaloka AI Technologies",
            "lead": "Laboratoire technologique et studio de création d'entreprises. Né en Afrique. Pensé pour le monde.",
            "blocks": [
                {"t": "h2", "c": "Qui sommes-nous ?"},
                {"t": "p", "c": "Kamaloka AI Technologies LLC est une entreprise technologique ivoirienne qui conçoit, développe et lance des produits numériques à fort impact. Nous combinons intelligence artificielle, cybersécurité, ingénierie logicielle et automatisation pour résoudre des problèmes concrets — en Côte d'Ivoire, en Afrique et à l'international."},
                {"t": "h2", "c": "Notre modèle"},
                {"t": "p", "c": "Nous ne sommes pas une agence de prestation classique. Kamaloka fonctionne comme un laboratoire et un venture studio : nous identifions des marchés sous-adressés, construisons la technologie, lançons le produit et accélérons lorsque le marché répond."},
                {"t": "ul", "items": ["Observer les problèmes réels sur le terrain", "Imaginer une solution repensée avec l'IA", "Construire et déployer rapidement", "Mesurer, apprendre, accélérer"]},
                {"t": "h2", "c": "Où nous opérons"},
                {"t": "p", "c": "Siège opérationnel à Bingerville / Abidjan (Côte d'Ivoire), avec une présence aux États-Unis (Albuquerque, NM). Cette double ancrage nous permet de construire pour les réalités africaines tout en visant des standards globaux."},
                {"t": "cta", "label": "Découvrir nos produits", "href": "/fr/produits/"},
            ],
        },
        "en": {
            "path": "/en/about/",
            "title": "About Kamaloka AI Technologies — AI Lab & Venture Studio",
            "description": "Kamaloka AI Technologies LLC: technology lab and venture studio based in Abidjan. AI, cybersecurity, software and automation — born in Africa, built for the world.",
            "h1": "Kamaloka AI Technologies",
            "lead": "Technology lab and venture studio. Born in Africa. Built for the world.",
            "blocks": [
                {"t": "h2", "c": "Who we are"},
                {"t": "p", "c": "Kamaloka AI Technologies LLC is an Ivorian technology company that designs, builds and launches high-impact digital products. We combine artificial intelligence, cybersecurity, software engineering and automation to solve real problems — in Côte d'Ivoire, across Africa and internationally."},
                {"t": "h2", "c": "Our model"},
                {"t": "p", "c": "We are not a traditional services agency. Kamaloka operates as a lab and venture studio: we identify underserved markets, build the technology, launch the product and accelerate when the market responds."},
                {"t": "ul", "items": ["Observe real-world problems on the ground", "Reimagine solutions with AI", "Build and ship fast", "Measure, learn, accelerate"]},
                {"t": "h2", "c": "Where we operate"},
                {"t": "p", "c": "Operational headquarters in Bingerville / Abidjan (Côte d'Ivoire), with a US presence in Albuquerque, NM. This dual footprint lets us build for African realities while meeting global standards."},
                {"t": "cta", "label": "Explore our products", "href": "/en/products/"},
            ],
        },
    },
    {
        "id": "products",
        "type": "CollectionPage",
        "priority": "0.9",
        "fr": {
            "path": "/fr/produits/",
            "title": "Produits Kamaloka — IA, cybersécurité, automatisation & confiance numérique",
            "description": "Découvrez l'écosystème Kamaloka : Kagliostro, OrchestrIA, Vibeminator, FOTIP CI, Desky et Argos. Technologies IA conçues à Abidjan pour des usages réels.",
            "h1": "Nos produits",
            "lead": "Un écosystème de technologies spécialisées. Chaque produit résout un problème précis.",
            "blocks": [
                {"t": "cards", "items": [
                    {"name": "FOTIP CI", "desc": "Vérifier numéros, liens et messages suspects avant de faire confiance.", "href": "/fr/produits/fotip-ci/"},
                    {"name": "KAGLIOSTRO", "desc": "Cybersécurité augmentée par des agents intelligents.", "href": "/fr/produits/kagliostro/"},
                    {"name": "ORCHESTRIA", "desc": "Publicité digitale simplifiée par l'IA.", "href": "/fr/produits/orchestria/"},
                    {"name": "VIBEMINATOR", "desc": "De l'idée à l'application en une instruction.", "href": "/fr/produits/vibeminator/"},
                    {"name": "DESKY", "desc": "Support client hybride IA + humain.", "href": "/fr/produits/desky/"},
                    {"name": "ARGOS", "desc": "Veille et intelligence économique automatisée.", "href": "/fr/produits/argos/"},
                ]},
                {"t": "cta", "label": "Nous contacter", "href": "/fr/contact/"},
            ],
        },
        "en": {
            "path": "/en/products/",
            "title": "Kamaloka Products — AI, Cybersecurity, Automation & Digital Trust",
            "description": "Explore the Kamaloka ecosystem: Kagliostro, OrchestrIA, Vibeminator, FOTIP CI, Desky and Argos. AI technologies built in Abidjan for real-world use cases.",
            "h1": "Our products",
            "lead": "An ecosystem of specialized technologies. Each product solves a specific problem.",
            "blocks": [
                {"t": "cards", "items": [
                    {"name": "FOTIP CI", "desc": "Verify suspicious numbers, links and messages before you trust.", "href": "/en/products/fotip-ci/"},
                    {"name": "KAGLIOSTRO", "desc": "Cybersecurity powered by intelligent agents.", "href": "/en/products/kagliostro/"},
                    {"name": "ORCHESTRIA", "desc": "Digital advertising simplified by AI.", "href": "/en/products/orchestria/"},
                    {"name": "VIBEMINATOR", "desc": "From idea to application in one instruction.", "href": "/en/products/vibeminator/"},
                    {"name": "DESKY", "desc": "Hybrid AI + human customer support.", "href": "/en/products/desky/"},
                    {"name": "ARGOS", "desc": "Automated monitoring and business intelligence.", "href": "/en/products/argos/"},
                ]},
                {"t": "cta", "label": "Contact us", "href": "/en/contact/"},
            ],
        },
    },
    {
        "id": "fotip-ci",
        "type": "SoftwareApplication",
        "priority": "0.85",
        "product_name": "FOTIP CI",
        "fr": {
            "path": "/fr/produits/fotip-ci/",
            "title": "FOTIP CI — Anti-arnaque Mobile Money & vérification numérique en Côte d'Ivoire",
            "description": "FOTIP CI aide à détecter arnaques Mobile Money, fraudes par SMS et liens suspects en Côte d'Ivoire. Vérifiez avant de transférer ou de cliquer.",
            "h1": "FOTIP CI",
            "lead": "Vérifier avant de faire confiance. Protection contre les arnaques Mobile Money et fraudes numériques en CI.",
            "blocks": [
                {"t": "p", "c": "En Côte d'Ivoire, l'explosion du Mobile Money (Orange Money, MTN MoMo, Wave) a créé une nouvelle surface d'attaque pour les arnaqueurs : faux agents, usurpation d'identité, liens de paiement frauduleux, messages WhatsApp et SMS trompeurs."},
                {"t": "h2", "c": "Ce que FOTIP CI analyse"},
                {"t": "ul", "items": ["Numéros de téléphone et comptes suspects", "Liens raccourcis et URLs de phishing", "Messages type « vous avez gagné » ou « débloquez votre compte »", "Signaux de fraude récurrents sur le marché ivoirien"]},
                {"t": "h2", "c": "Pour qui ?"},
                {"t": "p", "c": "Particuliers, commerçants, PME et institutions qui veulent réduire les pertes liées à la fraude digitale sans devenir experts en cybersécurité."},
                {"t": "cta", "label": "Lire : arnaques Mobile Money en CI", "href": "/fr/ressources/arnaques-mobile-money-cote-divoire/"},
            ],
        },
        "en": {
            "path": "/en/products/fotip-ci/",
            "title": "FOTIP CI — Mobile Money Scam Detection & Digital Trust in Côte d'Ivoire",
            "description": "FOTIP CI helps detect Mobile Money scams, SMS fraud and suspicious links in Côte d'Ivoire. Verify before you transfer or click.",
            "h1": "FOTIP CI",
            "lead": "Verify before you trust. Protection against Mobile Money scams and digital fraud in West Africa.",
            "blocks": [
                {"t": "p", "c": "Across Africa, mobile money adoption (Orange Money, MTN MoMo, Wave and others) has created new fraud surfaces: fake agents, identity theft, fraudulent payment links, deceptive WhatsApp and SMS messages."},
                {"t": "h2", "c": "What FOTIP CI analyzes"},
                {"t": "ul", "items": ["Suspicious phone numbers and accounts", "Short links and phishing URLs", "Prize scam and account-lock messages", "Recurring fraud patterns in local markets"]},
                {"t": "h2", "c": "Who is it for?"},
                {"t": "p", "c": "Individuals, merchants, SMBs and institutions looking to reduce digital fraud losses without becoming cybersecurity experts."},
                {"t": "cta", "label": "Read: mobile money fraud in Africa", "href": "/en/resources/mobile-money-fraud-africa/"},
            ],
        },
    },
    {
        "id": "kagliostro",
        "type": "SoftwareApplication",
        "priority": "0.8",
        "product_name": "Kagliostro",
        "fr": {
            "path": "/fr/produits/kagliostro/",
            "title": "Kagliostro — Cybersécurité IA & agents intelligents pour entreprises",
            "description": "Kagliostro : plateforme de cybersécurité augmentée par l'IA. Détection, analyse et correction assistée des vulnérabilités par agents intelligents.",
            "h1": "Kagliostro",
            "lead": "La cybersécurité entre dans l'ère des agents intelligents.",
            "blocks": [
                {"t": "p", "c": "Kagliostro repense la sécurité offensive et défensive avec des systèmes capables d'analyser, détecter, tester et accompagner la correction des vulnérabilités — plus vite qu'un audit manuel traditionnel."},
                {"t": "h2", "c": "Capacités clés"},
                {"t": "ul", "items": ["Analyse automatisée de surfaces d'attaque", "Agents pour prioriser les risques réels", "Assistance à la remédiation", "Adapté aux équipes tech africaines en croissance"]},
                {"t": "cta", "label": "Cybersécurité & IA", "href": "/fr/cybersecurite-ia/"},
            ],
        },
        "en": {
            "path": "/en/products/kagliostro/",
            "title": "Kagliostro — AI Cybersecurity & Intelligent Agents for Business",
            "description": "Kagliostro: AI-augmented cybersecurity platform. Detection, analysis and assisted remediation of vulnerabilities through intelligent agents.",
            "h1": "Kagliostro",
            "lead": "Cybersecurity enters the age of intelligent agents.",
            "blocks": [
                {"t": "p", "c": "Kagliostro reimagines offensive and defensive security with systems that analyze, detect, test and assist remediation — faster than traditional manual audits."},
                {"t": "h2", "c": "Key capabilities"},
                {"t": "ul", "items": ["Automated attack surface analysis", "Agents to prioritize real risks", "Remediation assistance", "Built for growing African tech teams"]},
                {"t": "cta", "label": "AI cybersecurity", "href": "/en/ai-cybersecurity/"},
            ],
        },
    },
    {
        "id": "orchestria",
        "type": "SoftwareApplication",
        "priority": "0.8",
        "product_name": "OrchestrIA",
        "fr": {
            "path": "/fr/produits/orchestria/",
            "title": "OrchestrIA — Publicité digitale automatisée par intelligence artificielle",
            "description": "OrchestrIA simplifie le lancement, l'analyse et l'optimisation de campagnes publicitaires grâce à l'IA. Moins d'opérations manuelles, plus de décisions utiles.",
            "h1": "OrchestrIA",
            "lead": "La publicité numérique sans la complexité.",
            "blocks": [
                {"t": "p", "c": "OrchestrIA aide les marques et PME à orchestrer leurs campagnes Meta, Google et canaux locaux avec des systèmes intelligents qui réduisent le temps passé sur les tâches répétitives."},
                {"t": "h2", "c": "Bénéfices"},
                {"t": "ul", "items": ["Lancement accéléré de campagnes", "Analyse consolidée multi-canal", "Recommandations d'optimisation", "Accessible aux équipes marketing non techniques"]},
            ],
        },
        "en": {
            "path": "/en/products/orchestria/",
            "title": "OrchestrIA — AI-Powered Digital Advertising Automation",
            "description": "OrchestrIA simplifies launching, analyzing and optimizing ad campaigns with AI. Less manual ops, more useful decisions.",
            "h1": "OrchestrIA",
            "lead": "Digital advertising without the complexity.",
            "blocks": [
                {"t": "p", "c": "OrchestrIA helps brands and SMBs orchestrate Meta, Google and local channel campaigns with intelligent systems that cut time spent on repetitive tasks."},
                {"t": "h2", "c": "Benefits"},
                {"t": "ul", "items": ["Faster campaign launch", "Consolidated multi-channel analytics", "Optimization recommendations", "Accessible to non-technical marketing teams"]},
            ],
        },
    },
    {
        "id": "desky",
        "type": "SoftwareApplication",
        "priority": "0.8",
        "product_name": "Desky",
        "fr": {
            "path": "/fr/produits/desky/",
            "title": "Desky — Support client IA & expérience client intelligente",
            "description": "Desky combine agents IA et intervention humaine pour un support client plus rapide. Ticketing, réponses automatiques et escalade intelligente.",
            "h1": "Desky",
            "lead": "Le support client réinventé.",
            "blocks": [
                {"t": "p", "c": "Desky est une plateforme où l'intelligence artificielle et l'humain collaborent : réponses instantanées pour les demandes simples, escalade fluide pour les cas complexes."},
                {"t": "ul", "items": ["Réponses 24/7 en français et anglais", "Intégration WhatsApp et email", "Réduction du temps de première réponse", "Tableau de bord pour équipes support"]},
            ],
        },
        "en": {
            "path": "/en/products/desky/",
            "title": "Desky — AI Customer Support & Intelligent CX Platform",
            "description": "Desky combines AI agents and human intervention for faster customer support. Ticketing, automated replies and smart escalation.",
            "h1": "Desky",
            "lead": "Customer support reinvented.",
            "blocks": [
                {"t": "p", "c": "Desky is a platform where AI and humans collaborate: instant answers for simple requests, smooth escalation for complex cases."},
                {"t": "ul", "items": ["24/7 replies in French and English", "WhatsApp and email integration", "Reduced first-response time", "Support team dashboard"]},
            ],
        },
    },
    {
        "id": "vibeminator",
        "type": "SoftwareApplication",
        "priority": "0.8",
        "product_name": "Vibeminator",
        "fr": {
            "path": "/fr/produits/vibeminator/",
            "title": "Vibeminator — Création d'applications IA : de l'idée au produit",
            "description": "Vibeminator transforme une intention en application moderne. Interface, logique métier, services et déploiement — création logicielle augmentée par l'IA.",
            "h1": "Vibeminator",
            "lead": "Une idée. Une instruction. Un produit.",
            "blocks": [
                {"t": "p", "c": "Vibeminator accélère la création logicielle pour fondateurs et équipes produit : spécifications, interfaces, backend et déploiement dans un flux unifié assisté par IA."},
                {"t": "ul", "items": ["Prototypage rapide", "Génération de composants UI", "Logique métier et API", "Déploiement cloud"]},
            ],
        },
        "en": {
            "path": "/en/products/vibeminator/",
            "title": "Vibeminator — AI App Builder: From Idea to Product",
            "description": "Vibeminator turns intent into a modern application. UI, business logic, services and deployment — AI-augmented software creation.",
            "h1": "Vibeminator",
            "lead": "One idea. One instruction. One product.",
            "blocks": [
                {"t": "p", "c": "Vibeminator accelerates software creation for founders and product teams: specs, interfaces, backend and deployment in a unified AI-assisted flow."},
                {"t": "ul", "items": ["Rapid prototyping", "UI component generation", "Business logic and APIs", "Cloud deployment"]},
            ],
        },
    },
    {
        "id": "argos",
        "type": "SoftwareApplication",
        "priority": "0.8",
        "product_name": "Argos",
        "fr": {
            "path": "/fr/produits/argos/",
            "title": "Argos — Veille IA & intelligence économique automatisée",
            "description": "Argos surveille, structure et analyse de grandes quantités de données pour identifier signaux faibles, opportunités et risques marché.",
            "h1": "Argos",
            "lead": "Transformer l'information en opportunité.",
            "blocks": [
                {"t": "p", "c": "Argos est conçu pour dirigeants, analystes et équipes stratégie qui doivent suivre marchés, concurrents et tendances sans noyer leurs équipes sous l'information."},
                {"t": "ul", "items": ["Collecte multi-sources", "Résumés intelligents", "Alertes sur signaux faibles", "Rapports exportables"]},
            ],
        },
        "en": {
            "path": "/en/products/argos/",
            "title": "Argos — AI Monitoring & Business Intelligence Automation",
            "description": "Argos monitors, structures and analyzes large data volumes to surface weak signals, opportunities and market risks.",
            "h1": "Argos",
            "lead": "Turn information into opportunity.",
            "blocks": [
                {"t": "p", "c": "Argos is built for executives, analysts and strategy teams who must track markets, competitors and trends without drowning teams in noise."},
                {"t": "ul", "items": ["Multi-source collection", "Intelligent summaries", "Weak-signal alerts", "Exportable reports"]},
            ],
        },
    },
    {
        "id": "ai-agents",
        "type": "WebPage",
        "priority": "0.85",
        "fr": {
            "path": "/fr/agents-ia/",
            "title": "Agents IA — Kamaloka construit la prochaine couche de l'économie",
            "description": "Kamaloka développe des agents IA pour vendre, analyser, sécuriser, assister, construire et opérer. Découvrez notre vision des agents autonomes en entreprise.",
            "h1": "Agents IA",
            "lead": "L'intelligence artificielle devient une nouvelle couche de l'économie.",
            "blocks": [
                {"t": "p", "c": "Pendant des décennies, les logiciels attendaient des instructions précises. La nouvelle génération comprend un objectif, raisonne, utilise des outils et accomplit des missions complètes."},
                {"t": "h2", "c": "Types d'agents que nous construisons"},
                {"t": "ul", "items": ["Agents commerciaux et marketing", "Agents d'analyse et de veille", "Agents de cybersécurité", "Agents support client", "Agents de développement logiciel", "Agents d'opérations internes"]},
                {"t": "p", "c": "Kamaloka ne fait pas de l'IA pour cocher une case. Chaque agent doit créer un avantage mesurable : vitesse, coût, qualité ou accès à des capacités autrefois réservées aux grandes organisations."},
                {"t": "cta", "label": "Agent IA vs chatbot", "href": "/fr/ressources/agent-ia-vs-chatbot/"},
            ],
        },
        "en": {
            "path": "/en/ai-agents/",
            "title": "AI Agents — Kamaloka Builds the Next Layer of the Economy",
            "description": "Kamaloka builds AI agents to sell, analyze, secure, assist, build and operate. Discover our vision for autonomous agents in business.",
            "h1": "AI Agents",
            "lead": "Artificial intelligence is becoming a new layer of the economy.",
            "blocks": [
                {"t": "p", "c": "For decades, software waited for precise instructions. The new generation understands a goal, reasons, uses tools and completes full missions."},
                {"t": "h2", "c": "Agent types we build"},
                {"t": "ul", "items": ["Sales and marketing agents", "Analysis and monitoring agents", "Cybersecurity agents", "Customer support agents", "Software development agents", "Internal operations agents"]},
                {"t": "p", "c": "Kamaloka doesn't do AI for the sake of it. Every agent must create measurable advantage: speed, cost, quality or access to capabilities once reserved for large organizations."},
                {"t": "cta", "label": "AI agent vs chatbot", "href": "/en/resources/ai-agent-vs-chatbot/"},
            ],
        },
    },
    {
        "id": "contact",
        "type": "ContactPage",
        "priority": "0.9",
        "fr": {
            "path": "/fr/contact/",
            "title": "Contact Kamaloka AI Technologies — Abidjan & international",
            "description": "Contactez Kamaloka AI Technologies à Abidjan. Email, WhatsApp, LinkedIn. Partenariats, presse, recrutement et demandes produits.",
            "h1": "Contact",
            "lead": "Parlons de votre projet, partenariat ou produit.",
            "blocks": [
                {"t": "contact"},
                {"t": "p", "c": "Kamaloka AI Technologies LLC — Bingerville / Abidjan, Côte d'Ivoire · Albuquerque, NM, États-Unis."},
            ],
        },
        "en": {
            "path": "/en/contact/",
            "title": "Contact Kamaloka AI Technologies — Abidjan & Worldwide",
            "description": "Contact Kamaloka AI Technologies in Abidjan. Email, WhatsApp, LinkedIn. Partnerships, press, hiring and product inquiries.",
            "h1": "Contact",
            "lead": "Let's talk about your project, partnership or product.",
            "blocks": [
                {"t": "contact"},
                {"t": "p", "c": "Kamaloka AI Technologies LLC — Bingerville / Abidjan, Côte d'Ivoire · Albuquerque, NM, United States."},
            ],
        },
    },
    {
        "id": "mobile-money-fraud",
        "type": "Article",
        "priority": "0.75",
        "fr": {
            "path": "/fr/ressources/arnaques-mobile-money-cote-divoire/",
            "title": "Arnaques Mobile Money en Côte d'Ivoire — Guide de protection 2026",
            "description": "Comment repérer les arnaques Orange Money, MTN MoMo et Wave en CI. Signaux d'alerte, bonnes pratiques et rôle de FOTIP CI.",
            "h1": "Arnaques Mobile Money en Côte d'Ivoire",
            "lead": "Protégez vos transferts et vos comptes face à la fraude digitale.",
            "blocks": [
                {"t": "p", "c": "Le Mobile Money est devenu le nerf de l'économie digitale ivoirienne. Les arnaqueurs l'ont compris : usurpation d'agents, faux gains, liens de « déblocage de compte » et pression psychologique par appel ou WhatsApp."},
                {"t": "h2", "c": "Signaux d'alerte fréquents"},
                {"t": "ul", "items": ["Demande de code secret ou OTP par message", "Promesse de gain immédiat contre un « frais »", "Numéro inconnu se présentant comme support officiel", "Lien raccourci vers une fausse page de connexion", "Urgence artificielle (« votre compte sera bloqué »)"]},
                {"t": "h2", "c": "Bonnes pratiques"},
                {"t": "ul", "items": ["Ne jamais partager votre code PIN ou OTP", "Vérifier le numéro via un canal officiel", "Utiliser FOTIP CI pour analyser un lien ou numéro suspect", "Signaler les arnaques aux opérateurs et autorités"]},
                {"t": "cta", "label": "Découvrir FOTIP CI", "href": "/fr/produits/fotip-ci/"},
            ],
        },
        "en": {
            "path": "/en/resources/mobile-money-fraud-africa/",
            "title": "Mobile Money Fraud in Africa — Protection Guide 2026",
            "description": "How to spot Orange Money, MTN MoMo and Wave scams across Africa. Warning signs, best practices and how FOTIP CI helps.",
            "h1": "Mobile Money Fraud in Africa",
            "lead": "Protect your transfers and accounts from digital fraud.",
            "blocks": [
                {"t": "p", "c": "Mobile money is the backbone of Africa's digital economy. Fraudsters exploit it through fake agents, prize scams, account-lock links and psychological pressure via calls or WhatsApp."},
                {"t": "h2", "c": "Common warning signs"},
                {"t": "ul", "items": ["Requests for PIN or OTP via message", "Instant prize promises requiring a 'fee'", "Unknown numbers posing as official support", "Short links to fake login pages", "Artificial urgency ('your account will be blocked')"]},
                {"t": "h2", "c": "Best practices"},
                {"t": "ul", "items": ["Never share PIN or OTP", "Verify numbers through official channels", "Use FOTIP CI to analyze suspicious links or numbers", "Report scams to operators and authorities"]},
                {"t": "cta", "label": "Discover FOTIP CI", "href": "/en/products/fotip-ci/"},
            ],
        },
    },
    {
        "id": "ai-adoption-ci",
        "type": "Article",
        "priority": "0.75",
        "fr": {
            "path": "/fr/ressources/adoption-ia-cote-divoire/",
            "title": "Adoption de l'IA en Côte d'Ivoire — État des lieux & opportunités",
            "description": "Comment les entreprises ivoiriennes adoptent l'intelligence artificielle : cas d'usage, freins, talents et opportunités pour PME et institutions.",
            "h1": "Adoption de l'IA en Côte d'Ivoire",
            "lead": "Où en est l'intelligence artificielle sur le marché ivoirien ?",
            "blocks": [
                {"t": "p", "c": "L'IA n'est plus réservée aux multinationales. À Abidjan, banques, telcos, startups et administrations explorent l'automatisation, l'analyse de données et les agents intelligents."},
                {"t": "h2", "c": "Cas d'usage qui progressent"},
                {"t": "ul", "items": ["Support client automatisé (WhatsApp, call center)", "Détection de fraude Mobile Money", "Analyse documentaire et conformité", "Marketing digital optimisé par IA", "Cybersécurité assistée"]},
                {"t": "h2", "c": "Freins à lever"},
                {"t": "p", "c": "Coût perçu, manque de talents spécialisés, données fragmentées et méfiance envers les « boîtes noires ». Kamaloka construit des produits explicables, utiles et adaptés au contexte local."},
                {"t": "cta", "label": "Entreprise tech à Abidjan", "href": "/fr/entreprise-technologique-abidjan/"},
            ],
        },
        "en": {
            "path": "/en/resources/ai-adoption-ivory-coast/",
            "title": "AI Adoption in Côte d'Ivoire — Landscape & Opportunities",
            "description": "How Ivorian businesses adopt artificial intelligence: use cases, barriers, talent and opportunities for SMBs and institutions.",
            "h1": "AI Adoption in Côte d'Ivoire",
            "lead": "Where does artificial intelligence stand in the Ivorian market?",
            "blocks": [
                {"t": "p", "c": "AI is no longer reserved for multinationals. In Abidjan, banks, telcos, startups and public bodies explore automation, data analysis and intelligent agents."},
                {"t": "h2", "c": "Growing use cases"},
                {"t": "ul", "items": ["Automated customer support (WhatsApp, call centers)", "Mobile money fraud detection", "Document analysis and compliance", "AI-optimized digital marketing", "Assisted cybersecurity"]},
                {"t": "h2", "c": "Barriers to address"},
                {"t": "p", "c": "Perceived cost, talent gaps, fragmented data and distrust of black boxes. Kamaloka builds explainable, useful products adapted to local context."},
                {"t": "cta", "label": "AI company in Ivory Coast", "href": "/en/ai-company-ivory-coast/"},
            ],
        },
    },
    {
        "id": "agent-vs-chatbot",
        "type": "Article",
        "priority": "0.75",
        "fr": {
            "path": "/fr/ressources/agent-ia-vs-chatbot/",
            "title": "Agent IA vs chatbot — Quelle différence pour votre entreprise ?",
            "description": "Agent IA ou chatbot classique ? Comprenez les différences techniques et business pour choisir la bonne architecture en 2026.",
            "h1": "Agent IA vs chatbot",
            "lead": "Deux technologies, deux niveaux d'ambition.",
            "blocks": [
                {"t": "p", "c": "Un chatbot répond à des questions prévisibles avec des scripts ou une base de connaissances. Un agent IA comprend un objectif, planifie des étapes, utilise des outils (API, CRM, bases de données) et peut agir de manière autonome dans des limites définies."},
                {"t": "h2", "c": "Quand choisir un chatbot"},
                {"t": "p", "c": "FAQ, horaires, redirection vers un humain — besoins simples à volume élevé."},
                {"t": "h2", "c": "Quand choisir un agent IA"},
                {"t": "p", "c": "Qualification de leads, analyse de documents, exécution de tâches multi-étapes, intégration système — là où la valeur est dans l'action, pas seulement la réponse."},
                {"t": "cta", "label": "Nos agents IA", "href": "/fr/agents-ia/"},
            ],
        },
        "en": {
            "path": "/en/resources/ai-agent-vs-chatbot/",
            "title": "AI Agent vs Chatbot — What's the Difference for Your Business?",
            "description": "AI agent or classic chatbot? Understand technical and business differences to choose the right architecture in 2026.",
            "h1": "AI Agent vs Chatbot",
            "lead": "Two technologies, two levels of ambition.",
            "blocks": [
                {"t": "p", "c": "A chatbot answers predictable questions with scripts or a knowledge base. An AI agent understands a goal, plans steps, uses tools (APIs, CRM, databases) and can act autonomously within defined boundaries."},
                {"t": "h2", "c": "When to choose a chatbot"},
                {"t": "p", "c": "FAQ, hours, routing to a human — simple needs at high volume."},
                {"t": "h2", "c": "When to choose an AI agent"},
                {"t": "p", "c": "Lead qualification, document analysis, multi-step tasks, system integration — where value is in action, not just answers."},
                {"t": "cta", "label": "Our AI agents", "href": "/en/ai-agents/"},
            ],
        },
    },
    {
        "id": "ai-cybersecurity",
        "type": "WebPage",
        "priority": "0.85",
        "fr": {
            "path": "/fr/cybersecurite-ia/",
            "title": "Cybersécurité IA — Protection intelligente pour entreprises africaines",
            "description": "Kamaloka combine cybersécurité et intelligence artificielle : détection, agents de sécurité, réponse aux incidents. Solutions adaptées aux PME africaines.",
            "h1": "Cybersécurité & IA",
            "lead": "Sécuriser l'ère des agents intelligents.",
            "blocks": [
                {"t": "p", "c": "La surface d'attaque des entreprises africaines grandit avec le cloud, le Mobile Money et le télétravail. Les équipes sécurité restent rares et surchargées."},
                {"t": "p", "c": "Kamaloka développe Kagliostro et des capacités IA pour automatiser l'analyse, prioriser les risques réels et accélérer la remédiation — sans remplacer l'expertise humaine."},
                {"t": "cta", "label": "Kagliostro", "href": "/fr/produits/kagliostro/"},
            ],
        },
        "en": {
            "path": "/en/ai-cybersecurity/",
            "title": "AI Cybersecurity — Intelligent Protection for African Businesses",
            "description": "Kamaloka combines cybersecurity and AI: detection, security agents, incident response. Solutions adapted for African SMBs.",
            "h1": "AI Cybersecurity",
            "lead": "Securing the age of intelligent agents.",
            "blocks": [
                {"t": "p", "c": "African companies face growing attack surfaces with cloud, mobile money and remote work. Security teams remain scarce and overloaded."},
                {"t": "p", "c": "Kamaloka builds Kagliostro and AI capabilities to automate analysis, prioritize real risks and accelerate remediation — without replacing human expertise."},
                {"t": "cta", "label": "Kagliostro", "href": "/en/products/kagliostro/"},
            ],
        },
    },
    {
        "id": "ai-automation",
        "type": "WebPage",
        "priority": "0.85",
        "fr": {
            "path": "/fr/automatisation-ia/",
            "title": "Automatisation IA — Accélérer les opérations avec Kamaloka",
            "description": "Automatisation intelligente pour PME et scale-ups : workflows, agents, intégrations. Réduisez les tâches répétitives avec l'IA.",
            "h1": "Automatisation IA",
            "lead": "Automatiser ce qui ralentit vos équipes.",
            "blocks": [
                {"t": "p", "c": "L'automatisation classique (RPA) casse dès que le contexte change. L'automatisation IA combine compréhension du langage, raisonnement et connexion à vos outils métier."},
                {"t": "ul", "items": ["Traitement de demandes clients", "Génération et classement de documents", "Synchronisation CRM / ERP", "Reporting et alertes intelligentes"]},
                {"t": "cta", "label": "Nos produits", "href": "/fr/produits/"},
            ],
        },
        "en": {
            "path": "/en/ai-automation/",
            "title": "AI Automation — Accelerate Operations with Kamaloka",
            "description": "Intelligent automation for SMBs and scale-ups: workflows, agents, integrations. Cut repetitive tasks with AI.",
            "h1": "AI Automation",
            "lead": "Automate what slows your teams down.",
            "blocks": [
                {"t": "p", "c": "Classic automation (RPA) breaks when context changes. AI automation combines language understanding, reasoning and connection to your business tools."},
                {"t": "ul", "items": ["Customer request processing", "Document generation and classification", "CRM / ERP sync", "Smart reporting and alerts"]},
                {"t": "cta", "label": "Our products", "href": "/en/products/"},
            ],
        },
    },
    {
        "id": "resources",
        "type": "CollectionPage",
        "priority": "0.8",
        "fr": {
            "path": "/fr/ressources/",
            "title": "Ressources Kamaloka — Guides IA, cybersécurité & tech en Côte d'Ivoire",
            "description": "Articles, guides et analyses Kamaloka sur l'IA, la cybersécurité, le Mobile Money et l'écosystème tech ivoirien.",
            "h1": "Ressources",
            "lead": "Guides, analyses et perspectives depuis Abidjan.",
            "blocks": [
                {"t": "links", "items": [
                    {"label": "Arnaques Mobile Money en Côte d'Ivoire", "href": "/fr/ressources/arnaques-mobile-money-cote-divoire/"},
                    {"label": "Adoption de l'IA en Côte d'Ivoire", "href": "/fr/ressources/adoption-ia-cote-divoire/"},
                    {"label": "Agent IA vs chatbot", "href": "/fr/ressources/agent-ia-vs-chatbot/"},
                    {"label": "Écosystème startup IA ivoirien", "href": "/fr/ressources/ecosysteme-startup-ia-cote-divoire/"},
                ]},
            ],
        },
        "en": {
            "path": "/en/resources/",
            "title": "Kamaloka Resources — AI, Cybersecurity & Tech Guides",
            "description": "Kamaloka articles and guides on AI, cybersecurity, mobile money and the Ivorian tech ecosystem.",
            "h1": "Resources",
            "lead": "Guides, insights and perspectives from Abidjan.",
            "blocks": [
                {"t": "links", "items": [
                    {"label": "Mobile Money Fraud in Africa", "href": "/en/resources/mobile-money-fraud-africa/"},
                    {"label": "AI Adoption in Côte d'Ivoire", "href": "/en/resources/ai-adoption-ivory-coast/"},
                    {"label": "AI Agent vs Chatbot", "href": "/en/resources/ai-agent-vs-chatbot/"},
                    {"label": "Ivory Coast AI Startup Ecosystem", "href": "/en/resources/ivory-coast-ai-startup-ecosystem/"},
                ]},
            ],
        },
    },
    {
        "id": "startup-ecosystem",
        "type": "Article",
        "priority": "0.75",
        "fr": {
            "path": "/fr/ressources/ecosysteme-startup-ia-cote-divoire/",
            "title": "Écosystème startup IA en Côte d'Ivoire — Cartographie 2026",
            "description": "Startups IA, hubs tech, financements et talents à Abidjan. Panorama de l'écosystème intelligence artificielle ivoirien.",
            "h1": "Écosystème startup IA ivoirien",
            "lead": "Abidjan émerge comme hub tech ouest-africain.",
            "blocks": [
                {"t": "p", "c": "Incubateurs, programmes corporate, diaspora tech et adoption Mobile Money créent un terrain fertile pour les startups IA en Côte d'Ivoire."},
                {"t": "h2", "c": "Forces de l'écosystème"},
                {"t": "ul", "items": ["Marché mobile-first massif", "Demande B2B pour fintech et confiance numérique", "Talents dev en croissance", "Ambition régionale (UEMOA)"]},
                {"t": "h2", "c": "Défis"},
                {"t": "p", "c": "Accès au capital patient, données de qualité, et produits pensés localement plutôt qu'importés sans adaptation."},
                {"t": "p", "c": "Kamaloka participe à cet écosystème en construisant depuis Abidjan des produits exportables."},
                {"t": "cta", "label": "À propos de Kamaloka", "href": "/fr/a-propos/"},
            ],
        },
        "en": {
            "path": "/en/resources/ivory-coast-ai-startup-ecosystem/",
            "title": "Ivory Coast AI Startup Ecosystem — 2026 Overview",
            "description": "AI startups, tech hubs, funding and talent in Abidjan. Overview of Côte d'Ivoire's artificial intelligence ecosystem.",
            "h1": "Ivory Coast AI Startup Ecosystem",
            "lead": "Abidjan is emerging as a West African tech hub.",
            "blocks": [
                {"t": "p", "c": "Incubators, corporate programs, tech diaspora and mobile money adoption create fertile ground for AI startups in Côte d'Ivoire."},
                {"t": "h2", "c": "Ecosystem strengths"},
                {"t": "ul", "items": ["Massive mobile-first market", "B2B demand for fintech and digital trust", "Growing developer talent", "Regional ambition (UEMOA)"]},
                {"t": "h2", "c": "Challenges"},
                {"t": "p", "c": "Patient capital access, quality data, and locally designed products rather than unadapted imports."},
                {"t": "p", "c": "Kamaloka contributes by building exportable products from Abidjan."},
                {"t": "cta", "label": "About Kamaloka", "href": "/en/about/"},
            ],
        },
    },
    {
        "id": "tech-company-abidjan",
        "type": "WebPage",
        "priority": "0.85",
        "fr": {
            "path": "/fr/entreprise-technologique-abidjan/",
            "title": "Entreprise technologique à Abidjan — Kamaloka AI Technologies",
            "description": "Kamaloka : entreprise tech à Abidjan spécialisée en IA, cybersécurité et logiciels. Laboratoire et venture studio ivoirien à portée internationale.",
            "h1": "Entreprise technologique à Abidjan",
            "lead": "Construire depuis la Côte d'Ivoire. Viser le monde.",
            "blocks": [
                {"t": "p", "c": "Abidjan concentre talents, clients et ambition. Kamaloka AI Technologies y développe des produits IA — cybersécurité, confiance numérique, automatisation — conçus pour les réalités locales et les standards globaux."},
                {"t": "h2", "c": "Pourquoi Kamaloka ?"},
                {"t": "ul", "items": ["Équipe compacte, exécution rapide", "Produits propriétaires (FOTIP, Kagliostro, etc.)", "Double présence CI + US", "Vision venture studio long terme"]},
                {"t": "cta", "label": "Nous contacter", "href": "/fr/contact/"},
            ],
        },
        "en": {
            "path": "/en/ai-company-ivory-coast/",
            "title": "AI Company in Ivory Coast — Kamaloka AI Technologies Abidjan",
            "description": "Kamaloka: Abidjan tech company specializing in AI, cybersecurity and software. Ivorian lab and venture studio with global reach.",
            "h1": "AI Company in Ivory Coast",
            "lead": "Build from Côte d'Ivoire. Aim for the world.",
            "blocks": [
                {"t": "p", "c": "Abidjan concentrates talent, customers and ambition. Kamaloka AI Technologies builds AI products — cybersecurity, digital trust, automation — designed for local realities and global standards."},
                {"t": "h2", "c": "Why Kamaloka?"},
                {"t": "ul", "items": ["Compact team, fast execution", "Proprietary products (FOTIP, Kagliostro, etc.)", "Dual CI + US presence", "Long-term venture studio vision"]},
                {"t": "cta", "label": "Contact us", "href": "/en/contact/"},
            ],
        },
    },
]
